import * as fs from "node:fs";
import * as path from "node:path";

import { parseFrontmatter } from "@earendil-works/pi-coding-agent";

import { resolveAgentName, type AgentConfig } from "../core/agents-config/config.js";
import { type SenaiRole } from "../core/agents-config/suggestions.js";
import {
	GENERATED_ROLES,
	GENERATOR_VERSION,
	getBundledTechnologiesDir,
	getProjectSlug,
	getProjectTechnologiesDir,
	parseKeywords,
} from "../agents/generator.js";

import type { DiagnosticItem, DiagnosticSection } from "./_types.js";

// Senai-only checks for the sub-agent generator's outputs (team agents and
// technology resources). The architecture-factory checks moved to
// @adi-mudi/pi-chirpi; these stayed because they audit GENERATED_ROLES and
// the technology resources owned by pi-senai's sub-agent generator.

/** Project-relative paths of every generated team agent. Supplied to
 *  pi-chirpi's checkArchitectureDrift so drift advice points at the right
 *  regeneration command for team agents. */
export function generatedTeamAgentPaths(cwd: string): Set<string> {
	const slug = getProjectSlug(cwd);
	return new Set(
		GENERATED_ROLES.map((def) => path.join(".pi", "agents", `${slug}-${def.role}.md`)),
	);
}

export function checkGeneratedTeamContent(cwd: string, agentConfig: AgentConfig | null): DiagnosticSection {
	const items: DiagnosticItem[] = [];
	const slug = getProjectSlug(cwd);
	let found = 0;

	for (const def of GENERATED_ROLES) {
		const expectedName = `${slug}-${def.role}`;
		const actual = resolveAgentName(agentConfig, def.role as SenaiRole);
		if (actual !== expectedName) continue; // custom mapping — not a generated team agent

		const filePath = path.join(cwd, ".pi", "agents", `${expectedName}.md`);
		if (!fs.existsSync(filePath)) continue; // missing files are reported by the mapping sources section

		found++;
		const content = fs.readFileSync(filePath, "utf8");
		const problems: string[] = [];

		const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
		const frontmatter = frontmatterMatch ? frontmatterMatch[1] : "";
		if (!/^tools:/m.test(frontmatter)) {
			problems.push("frontmatter is missing a tools: line");
		}
		if (!content.includes("## Your mandate")) {
			problems.push("body is missing the '## Your mandate' section");
		}
		if (!content.includes("## Technology craft")) {
			problems.push("body is missing a '## Technology craft' section");
		}

		if (problems.length === 0) {
			if (!content.includes(`(generator v${GENERATOR_VERSION})`)) {
				items.push({
					status: "warning",
					message: `${expectedName}: generated by an older pi-senai version`,
					details: [
						"Re-run /senai-generate-sub-agents to update it in place.",
						"If you edited the file after generation, your edits are detected and kept.",
					],
				});
			} else {
				items.push({ status: "ok", message: `${expectedName}: content complete` });
			}
		} else {
			items.push({
				status: "error",
				message: `${expectedName}: content is incomplete`,
				details: [...problems, "Fix: re-run /senai-generate-sub-agents to regenerate it."],
			});
		}
	}

	// Orphaned generated agents: carry the "Generated by pi-senai" marker but
	// no generated role maps to them (e.g. the role was remapped to a custom
	// or built-in agent). Reported only — deletion stays a user decision.
	const agentsDir = path.join(cwd, ".pi", "agents");
	if (fs.existsSync(agentsDir)) {
		const mappedNames = new Set(
			GENERATED_ROLES.map((def) => resolveAgentName(agentConfig, def.role as SenaiRole)),
		);
		for (const entry of fs.readdirSync(agentsDir)) {
			if (!entry.endsWith(".md")) continue;
			const name = entry.slice(0, -3);
			if (mappedNames.has(name)) continue;
			let orphanContent = "";
			try {
				orphanContent = fs.readFileSync(path.join(agentsDir, entry), "utf8");
			} catch {
				continue;
			}
			if (!orphanContent.includes("Generated by pi-senai")) continue;
			items.push({
				status: "info",
				message: `Orphaned generated agent: ${name}`,
				details: [
					"No Senai role maps to this file.",
					`If you do not need it, delete .pi/agents/${entry}.`,
				],
			});
		}
	}

	if (found === 0) {
		items.push({
			status: "info",
			message: "No generated team agents found. Run /senai-generate-sub-agents to create them.",
		});
	}

	return { title: "Generated team agents", items };
}

/**
 * Pin check: every GENERATED_ROLES row carries the v5 fields (invocationHint
 * + outOfScope) and the running GENERATOR_VERSION matches the latest
 * generator. Catches future code regressions where a role is added without
 * the new fields, or where the version constant is bumped but the test
 * pinning is missed.
 */
export function checkGeneratedRolesCompleteness(cwd: string): DiagnosticSection {
	const items: DiagnosticItem[] = [];

	// 1. Every GENERATED_ROLES row has invocationHint + outOfScope.
	const missingFields: string[] = [];
	for (const def of GENERATED_ROLES) {
		const hasHint = typeof def.invocationHint === "string" && def.invocationHint.length > 0;
		const hasOOS = Array.isArray(def.outOfScope) && def.outOfScope.length >= 1;
		if (!hasHint) missingFields.push(`${def.role} (no invocationHint)`);
		if (!hasOOS) missingFields.push(`${def.role} (no outOfScope)`);
	}
	if (missingFields.length === 0) {
		items.push({
			status: "ok",
			message: `All ${GENERATED_ROLES.length} GENERATED_ROLES rows have invocationHint + outOfScope.`,
		});
	} else {
		items.push({
			status: "warning",
			message: `${missingFields.length} GENERATED_ROLES row(s) missing required v5 fields.`,
			details: missingFields,
		});
	}

	// 2. Generated agents on latest version — duplicate count for stand-alone pin.
	const agentsDir = path.join(cwd, ".pi", "agents");
	if (fs.existsSync(agentsDir)) {
		const files = fs.readdirSync(agentsDir).filter((f) => f.endsWith(".md"));
		if (files.length > 0) {
			const onLatest = files.filter((f) => {
				try {
					return fs.readFileSync(path.join(agentsDir, f), "utf8").includes(`(generator v${GENERATOR_VERSION})`);
				} catch {
					return false;
				}
			});
			if (onLatest.length < files.length) {
				items.push({
					status: "info",
					message: `Agent version distribution: ${onLatest.length} on v${GENERATOR_VERSION}, ${files.length - onLatest.length} on older.`,
				});
			}
		}
	}

	return { title: "Sub-agent generator completeness", items };
}

export function checkTechnologyResources(cwd: string): DiagnosticSection {
	const items: DiagnosticItem[] = [];

	const dirs: Array<{ dir: string; label: string }> = [
		{ dir: getBundledTechnologiesDir(), label: "bundled" },
		{ dir: getProjectTechnologiesDir(cwd), label: "project" },
	];

	let bundledGenericFound = false;
	let resourceCount = 0;

	for (const { dir, label } of dirs) {
		if (!fs.existsSync(dir)) continue;
		for (const entry of fs.readdirSync(dir)) {
			if (!entry.endsWith(".md") || entry === "_template.md") continue;
			const filePath = path.join(dir, entry);
			const problems: string[] = [];
			try {
				const content = fs.readFileSync(filePath, "utf8");
				const { frontmatter } = parseFrontmatter<Record<string, unknown>>(content);
				const id = String(frontmatter.id ?? "").trim();
				if (!id) problems.push("frontmatter is missing an id");
				const keywords = parseKeywords(frontmatter.keywords);
				const hasKeywords = keywords.length > 0;
				if (!hasKeywords) problems.push("frontmatter has no keywords (matching will never find it)");
				const normalizeKey = (s: string) => s.toLowerCase().replace(/[-\s]+/g, " ").trim();
				if (id && hasKeywords && !keywords.some((k) => normalizeKey(k) === normalizeKey(id))) {
					problems.push(`keywords do not include the resource id "${id}" (matching by name will miss it)`);
				}
				const body = content.replace(/^---\n[\s\S]*?\n---\n*/, "").trim();
				if (!body) problems.push("body is empty");

				// Technical validation: craft sections and sourcing.
				if (body) {
					const missingSections: string[] = [];
					if (!/^##\s+Core rules/im.test(body)) missingSections.push("## Core rules");
					if (!/^##\s+Testing patterns/im.test(body)) missingSections.push("## Testing patterns");
					if (!/^###\s+Integration testing/im.test(body)) missingSections.push("### Integration testing");
					if (!/^##\s+(Tooling and limits|Common mistakes)/im.test(body)) {
						missingSections.push("## Tooling and limits or ## Common mistakes");
					}
					if (missingSections.length > 0) {
						problems.push(`missing template section(s): ${missingSections.join(", ")}`);
					}
					if (id !== "generic" && !/https?:\/\//.test(body)) {
						problems.push("no official source URL cited (sourcing rule)");
					}
				}

				if (label === "bundled" && id === "generic" && problems.length === 0) {
					bundledGenericFound = true;
				}
			} catch {
				problems.push("file could not be parsed");
			}

			if (problems.length === 0) {
				resourceCount++;
			} else {
				items.push({
					status: "warning",
					message: `${label} resource ${entry} has problems`,
					details: problems,
				});
			}
		}
	}

	if (!bundledGenericFound) {
		items.push({
			status: "error",
			message: "The bundled generic.md fallback resource is missing or invalid.",
			details: ["Restore resources/technologies/generic.md in the extension."],
		});
	}

	if (resourceCount > 0) {
		items.push({ status: "ok", message: `${resourceCount} technology resource(s) valid.` });
	}

	return { title: "Technology resources", items };
}
