import * as fs from "node:fs";
import * as path from "node:path";
import type { RpcClient } from "./rpc-client.js";
import type { TestHome } from "./test-home.js";

/** Minimal Node project layout: enough structure for scout/prompt tests to
 *  not crash on `ls`, small enough that the lifecycle stays fast. */
export function makeMinimalProjectFiles(): Array<{ path: string; content: string }> {
	return [
		{
			path: "package.json",
			content: JSON.stringify({
				name: "pi-senai-e2e-fixture",
				version: "0.0.0",
				type: "module",
				private: true,
			}, null, 2) + "\n",
		},
		{ path: "README.md", content: "# E2E fixture\n\nA minimal Node project for Pi Senai E2E tests.\n" },
		{ path: "src/index.js", content: "export const hello = () => 'hi';\n" },
	];
}

/** Seed the three .pi/senai config files so stage commands do not abort on
 *  the agent/files gate. Uses the built-in defaults so the spawn guard can
 *  match them deterministically. */
export function seedSenaiConfig(home: TestHome): void {
	const piSenai = path.join(home.cwd, ".pi", "senai");
	fs.mkdirSync(piSenai, { recursive: true });
	fs.writeFileSync(
		path.join(piSenai, "agents.json"),
		JSON.stringify({ _comment: "Generated by E2E fixture.", version: 1, agents: {} }, null, 2) + "\n",
		"utf8",
	);
	fs.writeFileSync(
		path.join(piSenai, "files.json"),
		JSON.stringify({
			_comment: "Generated by E2E fixture.",
			version: 2,
			codePaths: ["src/"],
			inputDocuments: ["README.md"],
			testPaths: ["test/"],
			excludedPaths: [".git/", "node_modules/", "dist/"],
		}, null, 2) + "\n",
		"utf8",
	);
	fs.writeFileSync(
		path.join(piSenai, "agents_files.json"),
		JSON.stringify({ _comment: "Generated by E2E fixture.", version: 2, documents: {} }, null, 2) + "\n",
		"utf8",
	);
}

/** Write a complete set of artifacts for one stage so /senai-approve can
 *  advance. `kind` matches the artifact group in listMissingStageArtifacts. */
export function writePlanArtifacts(
	cwd: string,
	runId: string,
	kind: "plan" | "implement" | "document" | "deliver",
): void {
	const runDir = path.join(cwd, ".IDE_Plans/pi-senai/runs", runId);
	const planDir = path.join(runDir, "plan");
	const implementDir = path.join(runDir, "implement");
	const documentDir = path.join(runDir, "document");
	const deliverDir = path.join(runDir, "deliver");

	if (kind === "plan" || kind === "implement" || kind === "document" || kind === "deliver") {
		fs.mkdirSync(path.join(planDir, "scouts"), { recursive: true });
		fs.mkdirSync(path.join(planDir, "reviews"), { recursive: true });
		fs.writeFileSync(path.join(planDir, "plan.md"), "# Plan\n");
		fs.writeFileSync(path.join(planDir, "plan-overview.md"), "# Overview\n");
		fs.writeFileSync(path.join(planDir, "discussion-notes.md"), "# Discussion\n");
		for (let i = 1; i <= 4; i++) {
			fs.writeFileSync(path.join(planDir, "scouts", `scout-angle_${i}.md`), `# Scout ${i}\n`);
		}
		fs.writeFileSync(path.join(planDir, "reviews", "review-correctness.md"), "# Correctness\n");
		fs.writeFileSync(path.join(planDir, "reviews", "review-security.md"), "# Security\n");
		fs.writeFileSync(path.join(planDir, "reviews", "review-tests.md"), "# Tests\n");
	}
	if (kind === "implement" || kind === "document" || kind === "deliver") {
		fs.mkdirSync(path.join(implementDir, "src"), { recursive: true });
		fs.mkdirSync(path.join(implementDir, "test"), { recursive: true });
		fs.writeFileSync(path.join(implementDir, "src/index.js"), "console.log('hello');\n");
		fs.writeFileSync(path.join(implementDir, "test/index.test.js"), "// tests\n");
	}
	if (kind === "document" || kind === "deliver") {
		fs.mkdirSync(documentDir, { recursive: true });
		fs.writeFileSync(path.join(documentDir, "README.md"), "# README\n");
		fs.writeFileSync(path.join(documentDir, "CHANGELOG.md"), "# CHANGELOG\n");
	}
	if (kind === "deliver") {
		fs.mkdirSync(deliverDir, { recursive: true });
		fs.writeFileSync(path.join(deliverDir, "security-report.md"), "# Security Report\n");
		fs.writeFileSync(path.join(deliverDir, "deliver-summary.md"), "# Deliver Summary\n");
	}
}

/** Run /senai-approve (with confirmations = auto-yes via stdin if needed)
 *  until the current stage reaches `target`. Not every stage accepts
 *  approval artifacts without a prior subagent pass; in those cases the
 *  caller should `writePlanArtifacts` between approvals. */
export async function approveUntilStage(client: RpcClient, target: string): Promise<void> {
	const order = ["planning", "planned", "implementing", "implemented", "documenting", "documented", "delivering", "delivered"];
	for (let i = 0; i < order.length; i++) {
		const state = await client.getState();
		if (state.currentStage === target) return;
		if (state.currentStage === "delivered") return;
		await client.request("prompt", { text: "/senai-approve" });
		await client.waitForIdle();
	}
}

/** Write a seeded adaptive spawn cadence state file at
 *  `.IDE_Plans/pi-senai/spawn-cadence.json`. Matches the v1 schema the
 *  extension expects. `state` lets the caller override tier, counters,
 *  and history; defaults give the canonical fresh-project state. */
export function seedCadenceState(
	cwd: string,
	state: {
		tier?: "A" | "B" | "C" | "D";
		consecutiveCleanRuns?: number;
		last429At?: string | null;
		lastPromotableAt?: string | null;
		history?: Array<{ ts: string; from: string; to: string; reason: string }>;
	} = {},
): void {
	const cadencePath = path.join(cwd, ".IDE_Plans", "pi-senai", "spawn-cadence.json");
	fs.mkdirSync(path.dirname(cadencePath), { recursive: true });
	const value = {
		_comment: "Seeded by E2E fixture.",
		version: 1,
		tier: state.tier ?? "A",
		consecutiveCleanRuns: state.consecutiveCleanRuns ?? 0,
		last429At: state.last429At ?? null,
		lastPromotableAt: state.lastPromotableAt ?? null,
		history: state.history ?? [],
	};
	fs.writeFileSync(cadencePath, JSON.stringify(value, null, 2) + "\n", "utf8");
}
