/**
 * Brainstorm lifecycle integration test (Phase 8)
 *
 * End-to-end coverage of the 8-phase brainstorm upgrade, wired through the
 * mocked command handlers. No real pi binary needed — this runs as part of
 * `npm test` (the e2e/ RPC harness is gated behind RUN_E2E=1).
 *
 * Steps verified:
 *   1. /senai-brainstorm refuses empty seed (Phase 2)
 *   2. /senai-brainstorm mints a brainstorm run id (Phase 1)
 *   3. The registry block surfaces in the stage prompt (Phase 3)
 *   4. Dispatcher accepts a scout-2 dispatch + strips Write tools (Phase 4)
 *   5. /senai-brainstorm-approve hard-rejects on _TBD_ placeholder (Phase 2)
 *   6. /senai-brainstorm-approve succeeds on a fully-filled brief (Phase 2)
 *   7. brainstorm-dispatch.md is written with the audit summary (Phase 5)
 *   8. /senai-doctor reads the audit log and surfaces findings (Phase 6)
 *   9. /senai-plan adopts the brainstorm run id (Phase 1)
 *  10. web-research agent is generated by /senai-generate-sub-agents (Phase 7.5)
 */

import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";
import {
	loadState,
	startBrainstorm,
} from "../../src/core/state.js";
import {
	getBrainstormDir,
	getBrainstormMissionBriefPath,
	getBrainstormDispatchLogPath,
	getRunDir,
} from "../../src/core/paths.js";
import {
	createAuditSession,
	buildSummary,
	writeAuditLog,
} from "../../src/brainstorm/audit.js";
import {
	prepareDispatch,
	formatPreparedDispatch,
} from "../../src/brainstorm/dispatcher.js";
import { loadBrainstormRegistry, matchSpecialist } from "../../src/brainstorm/registry.js";
import { checkBrainstormAudit, parseAuditLog } from "../../src/doctor/checks-brainstorm-audit.js";
import { runSenaiDiagnostic } from "../../src/doctor/index.js";
import {
	GENERATED_ROLES,
	planAgentGeneration,
	writeGeneratedAgents,
} from "../../src/agents/generator.js";
import { registerBrainstormCommands } from "../../src/commands/brainstorm.js";
import { registerPlanCommand } from "../../src/commands/stage-commands.js";
import { registerCommands } from "../../src/commands/index.js";
import { saveAgentConfig } from "../../src/agents/config.js";
import { saveFilesConfig } from "../../src/agents/files-config.js";
import { saveAgentsFilesConfig } from "../../src/agents/agents-files-config.js";
import { DEFAULT_AGENTS } from "../../src/agents/suggestions.js";

interface TestHarness {
	tmpDir: string;
	notifications: Array<{ message: string; type: string }>;
	sentMessages: string[];
	commandHandlers: Record<string, (args: string, ctx: ExtensionContext) => Promise<void>>;
	confirmResponses: boolean[];
	confirmIndex: number;
}

function makeHarness(prefix: string): TestHarness {
	const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
	const notifications: Array<{ message: string; type: string }> = [];
	const sentMessages: string[] = [];
	const commandHandlers: Record<string, (args: string, ctx: ExtensionContext) => Promise<void>> = {};
	const confirmResponses: boolean[] = [];
	let confirmIndex = 0;
	fs.mkdirSync(path.join(tmpDir, ".pi/senai"), { recursive: true });

	const api: ExtensionAPI = {
		registerCommand: (name: string, cmd: { handler: (args: string, ctx: ExtensionContext) => Promise<void> }) => {
			commandHandlers[name] = cmd.handler;
		},
		registerTool: () => {},
		on: () => {},
		registerMessageRenderer: () => {},
		sendUserMessage: (message: string) => {
			sentMessages.push(message);
		},
		sendMessage: () => {},
	} as unknown as ExtensionAPI;

	// Register all commands once.
	registerBrainstormCommands(api);
	registerPlanCommand(api);
	registerCommands(api);

	return {
		tmpDir,
		notifications,
		sentMessages,
		commandHandlers,
		confirmResponses,
		get confirmIndex() {
			return confirmIndex;
		},
		set confirmIndex(v: number) {
			confirmIndex = v;
		},
	};
}

function writeDefaultSenaiConfig(tmpDir: string): void {
	saveAgentConfig(tmpDir, { version: 1, agents: { ...DEFAULT_AGENTS } });
	saveFilesConfig(tmpDir, {
		version: 2,
		codePaths: [],
		inputDocuments: [],
		testPaths: [],
		excludedPaths: [".git/", "node_modules/"],
	});
	saveAgentsFilesConfig(tmpDir, { version: 2, documents: {} });
}

function makeCtxFor(harness: TestHarness): ExtensionContext {
	return {
		cwd: harness.tmpDir,
		ui: {
			notify: (message: string, type: string) => {
				harness.notifications.push({ message, type });
			},
			confirm: async () => {
				const r = harness.confirmResponses[harness.confirmIndex++] ?? true;
				return r;
			},
			input: async () => "",
			editor: async () => "",
			select: async (_t: string, options: string[]) => options[0],
		},
		getContextUsage: () => undefined,
		compact: () => {},
	} as unknown as ExtensionContext;
}

describe("brainstorm upgrade — full lifecycle", () => {
	let harness: TestHarness;

	beforeEach(() => {
		harness = makeHarness("pi-senai-brainstorm-e2e-");
		writeDefaultSenaiConfig(harness.tmpDir);
	});

	afterEach(() => {
		fs.rmSync(harness.tmpDir, { recursive: true, force: true });
	});

	it("Phase 2 — /senai-brainstorm with empty seed is REJECTED", async () => {
		harness.notifications.length = 0;
		await harness.commandHandlers["senai-brainstorm"]("", makeCtxFor(harness));

		const warning = harness.notifications.find(
			(n) => n.type === "warning" && n.message.includes("seed topic"),
		);
		assert.ok(warning, "expected a warning notify about empty seed");
		// No brainstorm run id should be created.
		const state = loadState(harness.tmpDir);
		assert.strictEqual(state.brainstormRunId, undefined);
	});

	it("Phase 1 — /senai-brainstorm mints a brainstorm run id and persists it", async () => {
		harness.notifications.length = 0;
		harness.sentMessages.length = 0;
		await harness.commandHandlers["senai-brainstorm"](
			"refactor the lock module — deadlock in retry path",
			makeCtxFor(harness),
		);

		const state = loadState(harness.tmpDir);
		assert.ok(state.brainstormRunId, "brainstormRunId must be set");
		assert.ok(state.brainstormRunId!.includes("brainstorm-"));
		assert.ok(state.brainstormRunId!.includes("refactor"));
		// No mutation of stage — brainstorm is orthogonal.
		assert.strictEqual(state.currentStage, "none");
	});

	it("Phase 3 — stage prompt includes the brainstorm registry block + decision tree", async () => {
		harness.notifications.length = 0;
		harness.sentMessages.length = 0;
		await harness.commandHandlers["senai-brainstorm"](
			"deadlock in the lock module",
			makeCtxFor(harness),
		);

		assert.strictEqual(harness.sentMessages.length, 1);
		const prompt = harness.sentMessages[0];
		assert.ok(prompt.includes("Brainstorm-eligible agents"));
		assert.ok(prompt.includes("Specialist dispatch decision tree"));
		assert.ok(prompt.includes("Dispatch counter:"));
		assert.ok(prompt.includes("scout-2"));
		assert.ok(prompt.includes("community-researcher"));
		assert.ok(prompt.toLowerCase().includes("deadlock")); // suggested match
	});

	it("Phase 4 — dispatcher accepts scout-2 + strips Write/Edit", () => {
		const r = prepareDispatch(
			{
				agent: "scout",
				task: "scan src/ for deadlock patterns",
				tools: ["Read", "Write", "Grep", "Edit"],
			},
			"2026-09-06-19-30-brainstorm-test",
			0,
		);
		assert.ok(r.ok);
		if (r.ok) {
			assert.deepStrictEqual(r.prepared.tools, ["Read", "Grep"]);
			assert.strictEqual(r.prepared.subagentArgs.timeoutMs, 30_000);
		}
	});

	it("Phase 4 — dispatcher rejects web-research when dispatch cap is reached", () => {
		const r = prepareDispatch(
			{ agent: "web-research", task: "fetch docs" },
			"2026-09-06-19-30-brainstorm-test",
			3,
		);
		assert.strictEqual(r.ok, false);
	});

	it("Phase 1 — matchSpecialist picks scout-2 for a deadlock topic", () => {
		const registry = loadBrainstormRegistry(harness.tmpDir);
		assert.ok(registry.length >= 6, `registry should have at least 6 entries, got ${registry.length}`);
		const match = matchSpecialist(registry, "deadlock in the lock module");
		assert.ok(match);
		assert.strictEqual(match!.role, "scout-2");
	});

	it("Phase 2 + 5 — full happy path: brainstorm → approve → audit log written", async () => {
		// 1. Open brainstorm
		harness.notifications.length = 0;
		harness.sentMessages.length = 0;
		await harness.commandHandlers["senai-brainstorm"](
			"add user authentication",
			makeCtxFor(harness),
		);

		const state1 = loadState(harness.tmpDir);
		const brainstormRunId = state1.brainstormRunId!;
		assert.ok(brainstormRunId);

		// 2. Simulate parent LLM writing the brief.
		const briefPath = getBrainstormMissionBriefPath(harness.tmpDir, brainstormRunId);
		fs.mkdirSync(path.dirname(briefPath), { recursive: true });
		fs.writeFileSync(
			briefPath,
			[
				"<!-- pi-senai mission-brief: draft -->",
				"",
				"## Problem statement",
				"",
				"The app has no user authentication. Anyone can use the API.",
				"",
				"## Mission type",
				"",
				"feature",
				"",
				"## Success criteria",
				"",
				"- Users can sign up with email + password",
				"- Sessions expire after 24 hours",
				"- Passwords are hashed with bcrypt",
				"",
				"## Out-of-scope",
				"",
				"- OAuth / social login",
				"- 2FA",
				"",
				"## Open questions",
				"",
				"- Postgres or SQLite for users table?",
				"",
				"## Refined mission",
				"",
				"Add email + password auth with bcrypt-hashed passwords and 24h sessions.",
			].join("\n"),
			"utf8",
		);
		// Write a transcript file too so recordDiscussion has something to find.
		const transcriptDir = path.join(
			harness.tmpDir,
			".IDE_Plans/pi-senai/Brainstorm",
			brainstormRunId,
			"discussions",
		);
		fs.mkdirSync(transcriptDir, { recursive: true });
		fs.writeFileSync(
			path.join(transcriptDir, "discussion-01-auth.md"),
			"# Q&A\nQ: mission type?\nA: feature\n",
			"utf8",
		);

		// 3. Approve.
		harness.notifications.length = 0;
		await harness.commandHandlers["senai-brainstorm-approve"](
			"",
			makeCtxFor(harness),
		);

		// Should succeed.
		const ok = harness.notifications.find(
			(n) => n.type === "info" && n.message.includes("Mission brief finalized"),
		);
		assert.ok(ok, `expected success notification, got: ${JSON.stringify(harness.notifications)}`);

		// 4. Brief marker removed.
		const finalBrief = fs.readFileSync(briefPath, "utf8");
		assert.ok(!finalBrief.startsWith("<!-- pi-senai mission-brief: draft -->"));

		// 5. State has a discussion event recorded.
		const state2 = loadState(harness.tmpDir);
		assert.strictEqual(state2.discussions, 1);
		assert.ok(state2.discussionEvents && state2.discussionEvents.length === 1);

		// 6. Audit log written.
		const auditPath = getBrainstormDispatchLogPath(harness.tmpDir, brainstormRunId);
		assert.ok(fs.existsSync(auditPath), "audit log should exist");
		const auditContent = fs.readFileSync(auditPath, "utf8");
		assert.ok(auditContent.startsWith("<!-- pi-senai brainstorm-dispatch -->"));
		assert.ok(auditContent.includes("# Brainstorm Dispatch Log"));
		assert.ok(auditContent.includes(`- Run: ${brainstormRunId}`));
		assert.ok(auditContent.includes("- Total dispatches:"));
	});

	it("Phase 2 — /senai-brainstorm-approve HARD-REJECTS on _TBD_ placeholders", async () => {
		// Open brainstorm
		await harness.commandHandlers["senai-brainstorm"](
			"refactor auth",
			makeCtxFor(harness),
		);

		const state = loadState(harness.tmpDir);
		const brainstormRunId = state.brainstormRunId!;

		// Write brief with _TBD_ placeholders.
		const briefPath = getBrainstormMissionBriefPath(harness.tmpDir, brainstormRunId);
		fs.mkdirSync(path.dirname(briefPath), { recursive: true });
		fs.writeFileSync(
			briefPath,
			[
				"<!-- pi-senai mission-brief: draft -->",
				"",
				"## Problem statement",
				"",
				"_TBD_",
				"",
				"## Mission type",
				"",
				"feature",
				"",
				"## Success criteria",
				"",
				"- one thing works",
				"",
				"## Out-of-scope",
				"",
				"- nothing else",
				"",
				"## Open questions",
				"",
				"- none",
				"",
				"## Refined mission",
				"",
				"do the thing",
			].join("\n"),
			"utf8",
		);

		// Approve — should hard-reject.
		harness.notifications.length = 0;
		await harness.commandHandlers["senai-brainstorm-approve"](
			"",
			makeCtxFor(harness),
		);

		const warning = harness.notifications.find(
			(n) => n.type === "warning" && n.message.includes("not ready to finalize"),
		);
		assert.ok(warning, "expected hard-reject warning");
		// Marker stays.
		const stillDraft = fs.readFileSync(briefPath, "utf8");
		assert.ok(stillDraft.startsWith("<!-- pi-senai mission-brief: draft -->"));
		// No discussion event recorded.
		const state2 = loadState(harness.tmpDir);
		assert.strictEqual(state2.discussions, 0);
	});

	it("Phase 6 — /senai-doctor reads the audit log and reports clean", async () => {
		// Write a clean audit log directly via the audit module.
		const id = "2026-09-06-19-30-brainstorm-test";
		const dir = getBrainstormDir(harness.tmpDir, id);
		fs.mkdirSync(dir, { recursive: true });
		const session = createAuditSession(id, "test seed");
		const summary = buildSummary(session, {
			wallClockMs: 5000,
			briefSectionsFilled: 6,
			briefSectionsTotal: 6,
		});
		writeAuditLog(harness.tmpDir, session, summary);

		const section = checkBrainstormAudit(harness.tmpDir);
		const okItems = section.items.filter((i) => i.status === "ok");
		assert.ok(
			okItems.some((i) => i.message.includes("audit clean")),
			`expected a 'audit clean' ok item, got: ${JSON.stringify(section.items)}`,
		);
	});

	it("Phase 6 — /senai-doctor flags dispatch cap exceeded", async () => {
		const id = "2026-09-06-19-30-brainstorm-cap";
		const dir = getBrainstormDir(harness.tmpDir, id);
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(
			getBrainstormDispatchLogPath(harness.tmpDir, id),
			[
				"<!-- pi-senai brainstorm-dispatch -->",
				"",
				"# Brainstorm Dispatch Log",
				"",
				`- Run: ${id}`,
				`- Started: 2026-09-06T19:30:00.000Z`,
				`- Seed: "test"`,
				"",
				"## Decisions",
				"",
				"_(none)_",
				"",
				"## Summary",
				"",
				"- Total dispatches: 7",
				"- Inline reads: 0",
				"- Skipped: 0",
				"- Side-channel: 0",
				"- Wall-clock total: ~5000ms",
				"- Brief sections filled: 6 / 6",
			].join("\n") + "\n",
			"utf8",
		);

		const section = checkBrainstormAudit(harness.tmpDir);
		const warning = section.items.find(
			(i) => i.status === "warning" && i.message.includes("dispatch cap exceeded"),
		);
		assert.ok(warning, "expected cap-exceeded warning");
	});

	it("Phase 1 — /senai-plan adopts the brainstorm run id", async () => {
		// Seed a brainstorm run id + valid brief (already approved).
		const id = "2026-09-06-19-30-brainstorm-plan-adopt";
		const dir = getBrainstormDir(harness.tmpDir, id);
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(
			getBrainstormMissionBriefPath(harness.tmpDir, id),
			[
				"## Problem statement",
				"the retry path deadlocks",
				"",
				"## Mission type",
				"bugfix",
				"",
				"## Success criteria",
				"- no deadlock under 100 clients",
				"",
				"## Out-of-scope",
				"- nothing else",
				"",
				"## Open questions",
				"- none",
				"",
				"## Refined mission",
				"fix the deadlock",
			].join("\n"),
			"utf8",
		);

		// Persist brainstorm run id into state.json directly (skipping the
		// /senai-brainstorm command). startBrainstorm reuses the existing
		// id when state.brainstormRunId is already set.
		const seed = loadState(harness.tmpDir);
		seed.brainstormRunId = id;
		startBrainstorm(harness.tmpDir, "ignored — seed already set", seed);

		// Sanity: state should now carry the seeded run id.
		assert.strictEqual(loadState(harness.tmpDir).brainstormRunId, id);

		// Now run /senai-plan.
		harness.notifications.length = 0;
		await harness.commandHandlers["senai-plan"](
			"fix the deadlock",
			makeCtxFor(harness),
		);

		// Plan should adopt the brainstorm run id, not mint a new one.
		const runDir = getRunDir(harness.tmpDir, id);
		assert.ok(fs.existsSync(runDir), `runs/<id>/ should exist at ${runDir}`);
		const adopted = loadState(harness.tmpDir);
		assert.strictEqual(adopted.runId, id, "plan must adopt the brainstorm run id");
		assert.strictEqual(adopted.mission, "fix the deadlock");
		assert.strictEqual(adopted.currentStage, "planning");

		// Notify should mention the adoption.
		const adoptNotify = harness.notifications.find(
			(n) => n.message.includes("Adopted brainstorm run"),
		);
		assert.ok(adoptNotify, `expected an adoption notification, got: ${JSON.stringify(harness.notifications)}`);

		// Brief should be copied into runs/<id>/.
		const runBrief = path.join(runDir, "mission-brief.md");
		assert.ok(fs.existsSync(runBrief), "brief should be copied into the run folder");
	});

	it("Phase 7.5 — /senai-generate-sub-agents creates web-researcher + 14 others", async () => {
		const tmpDir = harness.tmpDir;
		const def = GENERATED_ROLES.find((r) => r.role === "community-researcher");
		assert.ok(def, "community-researcher must be in GENERATED_ROLES");

		const plans = planAgentGeneration(tmpDir, [def], [], null);
		const result = writeGeneratedAgents(tmpDir, plans);
		assert.strictEqual(result.created.length, 1);
		// result.created contains paths relative to cwd; the file lives at
		// `<cwd>/<rel>`. Combine with cwd.
		const rel = result.created[0];
		const filePath = path.isAbsolute(rel) ? rel : path.join(tmpDir, rel);
		assert.ok(filePath.endsWith("community-researcher.md"), `got ${filePath}`);

		const content = fs.readFileSync(filePath, "utf8");
		assert.ok(content.includes("name:"));
		assert.ok(content.includes("Web Research"));
		assert.ok(content.includes("tools: WebSearch, FetchURL, Read"));
		// Footer carries the v8 generator version + canonical body filename.
		assert.ok(content.includes("generator v8"));
		assert.ok(content.includes("web-researcher-body.md"));
	});

	it("Phase 5 — parseAuditLog reads a written file back into structured form", () => {
		const id = "2026-09-06-19-30-brainstorm-parse";
		const session = createAuditSession(id, "test seed");
		const summary = buildSummary(session, {
			wallClockMs: 3000,
			briefSectionsFilled: 6,
			briefSectionsTotal: 6,
		});
		const filePath = writeAuditLog(harness.tmpDir, session, summary);

		const parsed = parseAuditLog(fs.readFileSync(filePath, "utf8"));
		assert.ok(parsed);
		assert.strictEqual(parsed!.brainstormRunId, id);
		assert.strictEqual(parsed!.seed, "test seed");
		assert.strictEqual(parsed!.summary.totalDispatches, 0);
	});

	it("Phase 8 — runSenaiDiagnostic includes the Brainstorm audit section", async () => {
		// Create a clean audit log so the section has something to report.
		const id = "2026-09-06-19-30-brainstorm-diag";
		const dir = getBrainstormDir(harness.tmpDir, id);
		fs.mkdirSync(dir, { recursive: true });
		const session = createAuditSession(id, "test");
		const summary = buildSummary(session, {
			wallClockMs: 1000,
			briefSectionsFilled: 6,
			briefSectionsTotal: 6,
		});
		writeAuditLog(harness.tmpDir, session, summary);

		// We need a Senai setup for runSenaiDiagnostic — at minimum
		// agents.json. It's already written in beforeEach.
		const report = runSenaiDiagnostic(harness.tmpDir);
		const auditSection = report.sections.find((s) => s.title === "Brainstorm audit");
		assert.ok(auditSection, "doctor report must include the 'Brainstorm audit' section");
		const ok = auditSection!.items.find((i) => i.status === "ok" && i.message.includes("audit clean"));
		assert.ok(ok, "the clean audit should appear as an ok item");
	});

	it("Phase 4 — formatPreparedDispatch renders a useful prompt block", () => {
		const r = prepareDispatch(
			{ agent: "scout", task: "scan src/ for deadlock", expectedOutput: "list of files" },
			"2026-09-06-19-30-brainstorm-test",
			0,
		);
		assert.ok(r.ok);
		if (r.ok) {
			const out = formatPreparedDispatch(r.prepared);
			assert.ok(out.includes("Prepared dispatch"));
			assert.ok(out.includes("scout"));
			assert.ok(out.includes("scan src/ for deadlock"));
			assert.ok(out.includes("Expected output: list of files"));
			assert.ok(out.includes("subagent({"));
		}
	});
});
