/**
 * Arch-rules check (Phase 3) — runs the emitted architecture-rule config
 * against the target project during implement-stage verification.
 *
 * The config is generated by pi-chirpi (`arch-rules.ts`) and lives in the
 * target project: `.dependency-cruiser.json` (TS/JS) or `.importlinter`
 * (Python). This module never installs the tools: when the tool is absent
 * the check reports toolAvailable=false so the caller can warn-and-continue
 * with an honest message instead of silently skipping.
 */

import * as fs from "node:fs";
import * as path from "node:path";

export type ArchRulesTool = "dependency-cruiser" | "import-linter";

export interface ArchRulesResult {
    /** An emitted config file exists in the project root. */
    configFound: boolean;
    tool: ArchRulesTool | null;
    /** Project-relative config path when found. */
    configPath: string | null;
    toolAvailable: boolean;
    /** The tool actually ran (config found + tool available). */
    ran: boolean;
    violations: string[];
}

export type ArchRulesExecFn = (
    cmd: string,
    args: string[],
    cwd: string,
) => Promise<{ code: number; output: string }>;

const MAX_VIOLATIONS = 20;

async function defaultExec(cmd: string, args: string[], cwd: string): Promise<{ code: number; output: string }> {
    const { execFile } = await import("node:child_process");
    return new Promise((resolve) => {
        execFile(cmd, args, { cwd, timeout: 120_000, maxBuffer: 500_000 }, (err, stdout, stderr) => {
            const output = ((stdout ?? "") + (stderr ?? "")).trim();
            if (err && (err as NodeJS.ErrnoException).code === "ENOENT") {
                resolve({ code: -1, output });
                return;
            }
            const code = typeof err?.code === "number" ? err.code : err ? 1 : 0;
            resolve({ code, output });
        });
    });
}

function collectLines(output: string, pattern: RegExp): string[] {
    const lines = output
        .split(/\r?\n/)
        .map((l) => l.trim())
        .filter((l) => l.length > 0 && pattern.test(l))
        .slice(0, MAX_VIOLATIONS);
    return lines;
}

/** Run the emitted arch-rules config when the matching tool is installed.
 *  The exec function is injectable so tests can mock the runner instead of
 *  installing dependency-cruiser / import-linter. */
export async function checkArchRules(
    cwd: string,
    execFn: ArchRulesExecFn = defaultExec,
): Promise<ArchRulesResult> {
    const depcruiseConfig = ".dependency-cruiser.json";
    const importLinterConfig = ".importlinter";

    if (fs.existsSync(path.join(cwd, depcruiseConfig))) {
        const bin = path.join(cwd, "node_modules", ".bin", "depcruise");
        if (!fs.existsSync(bin)) {
            return {
                configFound: true,
                tool: "dependency-cruiser",
                configPath: depcruiseConfig,
                toolAvailable: false,
                ran: false,
                violations: [],
            };
        }
        const target = fs.existsSync(path.join(cwd, "src")) ? "src" : ".";
        const { code, output } = await execFn(bin, ["--validate", depcruiseConfig, target], cwd);
        const violations = code === 0 ? [] : collectLines(output, /error|violation/i);
        if (code !== 0 && violations.length === 0) {
            violations.push(`dependency-cruiser reported violations (exit code ${code})`);
        }
        return {
            configFound: true,
            tool: "dependency-cruiser",
            configPath: depcruiseConfig,
            toolAvailable: true,
            ran: true,
            violations,
        };
    }

    if (fs.existsSync(path.join(cwd, importLinterConfig))) {
        const probe = await execFn("lint-imports", ["--version"], cwd);
        if (probe.code !== 0) {
            return {
                configFound: true,
                tool: "import-linter",
                configPath: importLinterConfig,
                toolAvailable: false,
                ran: false,
                violations: [],
            };
        }
        const { code, output } = await execFn("lint-imports", ["--config", importLinterConfig], cwd);
        const violations = code === 0 ? [] : collectLines(output, /BROKEN|not allowed|error/i);
        if (code !== 0 && violations.length === 0) {
            violations.push(`import-linter reported broken contracts (exit code ${code})`);
        }
        return {
            configFound: true,
            tool: "import-linter",
            configPath: importLinterConfig,
            toolAvailable: true,
            ran: true,
            violations,
        };
    }

    return { configFound: false, tool: null, configPath: null, toolAvailable: false, ran: false, violations: [] };
}
