import * as fs from "node:fs";
import {
  getArtifactPaths,
  getStatePath,
  makeRunId,
  STAGES,
  STAGE_TRANSITIONS,
  type Stage,
} from "../core/paths.js";
import { atomicWriteJson } from "../io/atomic-write.js";

/** One recorded /senai-brainstorm event. `afterStage` is the stage that
 *  was active when the discussion ran; undefined for discussions recorded
 *  before any run started (no active run — brainstorm has its own run id
 *  in .IDE_Plans/pi-senai/Brainstorm/<brainstorm-run-id>/). */
export interface DiscussionEvent {
  ts: string;
  transcriptPath: string;
  briefPath: string;
  /** Brainstorm run id when the brief lives under .IDE_Plans/pi-senai/Brainstorm/;
   *  undefined for legacy pre-run briefs. */
  brainstormRunId?: string;
  afterStage?: Stage;
}

export interface SenaiState {
  version: number;
  mission: string;
  runId: string;
  currentStage: Stage;
  startedAt: string;
  updatedAt: string;
  stageResults: Record<string, string | null>;
  /** Total discussions finalized for the active run (resets when a new run
   *  starts). Pre-run / brainstorm discussions do not bump this counter. */
  discussions?: number;
  /** Append-only log of finalized discussions, oldest first. */
  discussionEvents?: DiscussionEvent[];
  /** Path to the mission-brief.md consumed by /senai-plan. Relative to cwd,
   *  slash-style. Set when /senai-plan adopts a brainstorm run id (points
   *  at .IDE_Plans/pi-senai/runs/<run-id>/mission-brief.md) or when it
   *  consumes a legacy pre-run brief. */
  missionBriefPath?: string;
  /** Brainstorm run id generated by /senai-brainstorm on entry. Persisted in
   *  state.json so /senai-plan can adopt it instead of minting a new one.
   *  Lives under .IDE_Plans/pi-senai/Brainstorm/<brainstorm-run-id>/ while
   *  brainstorm is active. Multiple brainstorms for the same project each
   *  get their own id, so there is no conflict. */
  brainstormRunId?: string;
}

const CURRENT_VERSION = 1;

export function defaultState(): SenaiState {
  return {
    version: CURRENT_VERSION,
    mission: "",
    runId: "",
    currentStage: "none",
    startedAt: "",
    updatedAt: "",
    stageResults: {},
    discussions: 0,
    discussionEvents: [],
  };
}

export function loadState(cwd: string): SenaiState {
  const statePath = getStatePath(cwd);
  try {
    const raw = fs.readFileSync(statePath, "utf8");
    const parsed = JSON.parse(raw) as SenaiState;
    if (parsed.version !== CURRENT_VERSION) {
      return migrateState(parsed);
    }
    // A garbage stage would crash advanceStage later; reset to a safe value.
    if (!(STAGES as string[]).includes(parsed.currentStage)) {
      parsed.currentStage = "none";
    }
    return parsed;
  } catch (err: any) {
    if (err.code === "ENOENT") {
      return defaultState();
    }
    throw err;
  }
}

/**
 * Persist the run state to `.IDE_Plans/pi-senai/state.json`.
 *
 * Lock contract: every caller that mutates `state.json` (advanceStage,
 * recordDiscussion, setMissionBriefPath, plus any future helper) must run
 * inside `withRunLock()` at the call site. The lock prevents two concurrent
 * Pi sessions from racing on this file. `saveState` itself only guarantees
 * atomicity against process crashes (temp file + rename).
 */
export function saveState(cwd: string, state: SenaiState): void {
  atomicWriteJson(getStatePath(cwd), state);
}

export function startRun(cwd: string, mission: string): SenaiState {
  const runId = makeRunId(mission);
  const now = new Date().toISOString();
  const state: SenaiState = {
    version: CURRENT_VERSION,
    mission,
    runId,
    currentStage: "none",
    startedAt: now,
    updatedAt: now,
    stageResults: {},
  };
  const artifacts = getArtifactPaths(cwd, runId);
  fs.mkdirSync(artifacts.planScoutsDir, { recursive: true });
  fs.mkdirSync(artifacts.planReviewsDir, { recursive: true });
  fs.mkdirSync(artifacts.implementDir, { recursive: true });
  fs.mkdirSync(artifacts.documentDir, { recursive: true });
  fs.mkdirSync(artifacts.deliverDir, { recursive: true });
  saveState(cwd, state);
  return state;
}

/** Generate a brainstorm run id from a seed. Format matches makeRunId but
 *  carries a `brainstorm-` prefix so brainstorm and plan run ids never
 *  collide on the same minute stamp. */
export function makeBrainstormRunId(seed: string): string {
  const id = makeRunId(`brainstorm-${seed || "session"}`);
  return id;
}

/** Start (or resume) a brainstorm session. Generates a brainstorm run id,
 *  creates the Brainstorm/<id>/ folder, and persists the id in state.json
 *  without touching currentStage (brainstorm is orthogonal to the stage
 *  machine — see skills/senai-brainstorm.md). The folder is created on
 *  demand by the next recordDiscussion call; this helper only registers
 *  the id and writes state. */
export function startBrainstorm(cwd: string, seed: string, state: SenaiState): SenaiState {
  // Reuse the existing brainstorm run id when one is already in flight
  // (the parent resumed a session mid-discussion). Otherwise mint a fresh one.
  const brainstormRunId = state.brainstormRunId || makeBrainstormRunId(seed);
  const next: SenaiState = {
    ...state,
    brainstormRunId,
    updatedAt: new Date().toISOString(),
  };
  saveState(cwd, next);
  return next;
}

/** Persist a reference to a brainstorm brief that fed the active run.
 *  Called from /senai-plan when it adopts a brainstorm run id. The brief
 *  has already been copied into the run folder by that point. */
export function setBrainstormBriefPath(
  cwd: string,
  state: SenaiState,
  missionBriefPath: string,
): SenaiState {
  const next: SenaiState = {
    ...state,
    missionBriefPath,
    updatedAt: new Date().toISOString(),
  };
  saveState(cwd, next);
  return next;
}

export function advanceStage(
  cwd: string,
  state: SenaiState,
  nextStage: Stage,
  stageResult?: string,
): { ok: true; state: SenaiState } | { ok: false; reason: string } {
  const allowed = STAGE_TRANSITIONS[state.currentStage];
  if (!allowed.includes(nextStage)) {
    return {
      ok: false,
      reason: `Cannot move from '${state.currentStage}' to '${nextStage}'. Valid next stages: ${allowed.join(", ") || "(none)"}.`,
    };
  }
  const nextState: SenaiState = {
    ...state,
    currentStage: nextStage,
    updatedAt: new Date().toISOString(),
  };
  // Record how the stage we are leaving ended (approval time + artifact
  // check outcome). Keyed by the stage being left, so each entry is written
  // once, at the moment the stage completes.
  if (stageResult !== undefined) {
    nextState.stageResults = { ...state.stageResults, [state.currentStage]: stageResult };
  }
  saveState(cwd, nextState);
  return { ok: true, state: nextState };
}

export function resetState(cwd: string): void {
  const statePath = getStatePath(cwd);
  try {
    fs.unlinkSync(statePath);
  } catch (err: any) {
    if (err.code !== "ENOENT") throw err;
  }
}

/** Append a finalized discussion event and bump the discussions counter.
 *  Pure state helper; the caller writes the file system changes before
 *  calling this, so on a partial failure the brief/transcript are on disk
 *  but the counter is stale (doctor warns on that). */
export function recordDiscussion(
  cwd: string,
  state: SenaiState,
  event: DiscussionEvent,
): { ok: true; state: SenaiState } | { ok: false; reason: string } {
  if (!event.ts || !event.transcriptPath || !event.briefPath) {
    return { ok: false, reason: "Discussion event is missing required fields." };
  }
  const events = state.discussionEvents ?? [];
  const next: SenaiState = {
    ...state,
    discussions: (state.discussions ?? 0) + 1,
    discussionEvents: [...events, event],
    updatedAt: new Date().toISOString(),
  };
  saveState(cwd, next);
  return { ok: true, state: next };
}

/** Persist a reference to the pre-run brief that fed the active run.
 *  Called from /senai-plan when it consumes a pre-run discussion. */
export function setMissionBriefPath(
  cwd: string,
  state: SenaiState,
  missionBriefPath: string,
): SenaiState {
  const next: SenaiState = {
    ...state,
    missionBriefPath,
    updatedAt: new Date().toISOString(),
  };
  saveState(cwd, next);
  return next;
}

function migrateState(old: any): SenaiState {
  const fresh = defaultState();
  if (old && typeof old === "object") {
    if (typeof old.mission === "string") fresh.mission = old.mission;
    if (typeof old.runId === "string") fresh.runId = old.runId;
    if (typeof old.currentStage === "string" && (STAGES as string[]).includes(old.currentStage)) {
      fresh.currentStage = old.currentStage as Stage;
    }
    if (typeof old.startedAt === "string") fresh.startedAt = old.startedAt;
    if (typeof old.updatedAt === "string") fresh.updatedAt = old.updatedAt;
    if (old.stageResults && typeof old.stageResults === "object") {
      fresh.stageResults = old.stageResults;
    }
    // Legacy states may lack the new fields; treat their absence as defaults.
    if (typeof old.discussions === "number") fresh.discussions = old.discussions;
    if (Array.isArray(old.discussionEvents)) {
      fresh.discussionEvents = old.discussionEvents
        .filter(
          (e: any) => e && typeof e.ts === "string" && typeof e.transcriptPath === "string" && typeof e.briefPath === "string",
        )
        .map((e: any) => ({
          ts: e.ts,
          transcriptPath: e.transcriptPath,
          briefPath: e.briefPath,
          afterStage: typeof e.afterStage === "string" ? e.afterStage : undefined,
        }));
    }
    if (typeof old.missionBriefPath === "string") fresh.missionBriefPath = old.missionBriefPath;
    if (typeof old.brainstormRunId === "string") fresh.brainstormRunId = old.brainstormRunId;
  }
  return fresh;
}
