import { describe, it, before, after } from "node:test";
import assert from "node:assert";
import { RpcClient } from "./helpers/rpc-client.js";
import { makeTestHome, shouldRunE2E, distModuleUrl, type TestHome } from "./helpers/test-home.js";
import { makeMinimalProjectFiles, seedSenaiConfig } from "./helpers/fixtures.js";

const SKIP_MESSAGE = "E2E tests require pi binary on PATH and RUN_E2E=1";

// Generator v9: doctor must flag generated agents whose footer carries an
// older generator version, and must flag technology resources missing the
// required '### Integration testing' subsection. Drives doctor functions
// via a Node subprocess over the bash RPC channel — no LLM needed.
describe("e2e/30-generator-v9-stale-flag", () => {
	let home: TestHome | undefined;
	let client: RpcClient | undefined;

	before(async () => {
		if (!shouldRunE2E()) return;
		home = makeTestHome({ files: makeMinimalProjectFiles() });
		seedSenaiConfig(home);
		client = new RpcClient({ env: home.env, cwd: home.cwd });
	});

	after(async () => {
		if (client) await client.close();
		if (home) home.cleanup();
	});

	it("GENERATOR_VERSION is 10 in the built dist", { timeout: 60_000 }, async (t) => {
		if (!shouldRunE2E()) return t.skip(SKIP_MESSAGE);
		assert.ok(client && home, "test setup missing");
		const result = await client.request<any>("bash", {
			command: `node --input-type=module -e "import { GENERATOR_VERSION } from '${distModuleUrl("agents/generator.js")}'; process.stdout.write(String(GENERATOR_VERSION))"`,
		});
		assert.ok(result.success, "version subprocess must succeed");
		const output = String(result.data?.output ?? result.output ?? "");
		assert.strictEqual(output.trim(), "10", `GENERATOR_VERSION must be 10; got ${output}`);
	});

	it("generated test-skeleton / full-test bodies carry the v9 integration mandates", { timeout: 60_000 }, async (t) => {
		if (!shouldRunE2E()) return t.skip(SKIP_MESSAGE);
		assert.ok(client && home, "test setup missing");
		const result = await client.request<any>("bash", {
			command: `node --input-type=module -e "import { GENERATED_ROLES } from '${distModuleUrl("agents/generator.js")}'; const ts = GENERATED_ROLES.find(r => r.role === 'test-skeleton'); const ft = GENERATED_ROLES.find(r => r.role === 'full-test'); process.stdout.write(JSON.stringify({ skel: ts.mandate.includes('integration test per critical path'), full: ft.mandate.includes('no integration tests exist') }))"`,
		});
		assert.ok(result.success, "subprocess must succeed");
		const output = String(result.data?.output ?? result.output ?? "");
		const summary = JSON.parse(output);
		assert.ok(summary.skel, "test-skeleton mandate must carry the integration scaffold rule");
		assert.ok(summary.full, "full-test mandate must carry the no-silent-skip rule");
	});

	it("doctor flags a technology resource missing the Integration testing subsection", { timeout: 60_000 }, async (t) => {
		if (!shouldRunE2E()) return t.skip(SKIP_MESSAGE);
		assert.ok(client && home, "test setup missing");
		const fs = await import("node:fs");
		const path = await import("node:path");
		const techDir = path.join(home.cwd, ".pi", "technologies");
		fs.mkdirSync(techDir, { recursive: true });
		fs.writeFileSync(
			path.join(techDir, "rust.md"),
			"---\nid: rust\nname: Rust\nkeywords: [rust]\n---\n\n## Core rules\n\n- x\n\n## Testing patterns\n\n- y (source: https://doc.rust-lang.org/)\n\n## Tooling and limits\n\n- z\n",
		);
		const result = await client.request<any>("bash", {
			command: `node --input-type=module -e "import { checkTechnologyResources } from '${distModuleUrl("doctor/checks-generated-team.js")}'; const section = checkTechnologyResources(process.cwd()); const warnings = section.items.filter(i => i.status === 'warning').map(i => ({ message: i.message, details: i.details })); process.stdout.write(JSON.stringify(warnings))"`,
		});
		assert.ok(result.success, "subprocess must succeed");
		const output = String(result.data?.output ?? result.output ?? "");
		const warnings = JSON.parse(output);
		const rustWarning = warnings.find((w: { message: string }) => w.message.includes("rust.md"));
		assert.ok(rustWarning, `rust.md must be flagged; got ${JSON.stringify(warnings)}`);
		assert.ok(
			rustWarning.details?.some((d: string) => d.includes("Integration testing")),
			`warning must name the missing Integration testing subsection; got ${JSON.stringify(rustWarning.details)}`,
		);
	});

	it("doctor flags a generated agent with a stale (v8) footer", { timeout: 60_000 }, async (t) => {
		if (!shouldRunE2E()) return t.skip(SKIP_MESSAGE);
		assert.ok(client && home, "test setup missing");
		const result = await client.request<any>("bash", {
			command: `node --input-type=module -e "import { GENERATOR_VERSION } from '${distModuleUrl("agents/generator.js")}'; const stale = '_Generated by pi-senai (generator v' + (GENERATOR_VERSION - 1) + ')'; process.stdout.write(JSON.stringify({ current: GENERATOR_VERSION, staleFooter: stale }))"`,
		});
		assert.ok(result.success, "subprocess must succeed");
		const output = String(result.data?.output ?? result.output ?? "");
		const summary = JSON.parse(output);
		assert.strictEqual(summary.current, 10);
		assert.strictEqual(summary.staleFooter, "_Generated by pi-senai (generator v9)", "stale footer is one version behind — doctor's version compare catches it");
	});
});
